### ISSUE TITLE
Der TestClient startet mit höheren Scores wenn auf dem Server bereits Spiele liefen

### ISSUE THREAD

**Issue by xeruf** [software-challenge/backend#158]
Da der TestClient keinen eigenen Server betreibt und sich für die Punkte auf den Server verlässt, der ja eventuell schon einige Spiele hinter sich hat, startet er oft bei unterschiedlichen Punktzahlen.

**Comment by SKoschnicke** [comment]
Man koennte eine Moeglichkeit einbauen, dass man vor dem Start einer neuen Testreihe die alten Punktestaende loescht, wuerde das helfen?

**Comment by Xerus2000** [comment]
Jap, das sollte dann wahrscheinlich auf der Serverseite passieren, sobald sich der alte Adminclient getrennt hat und sich ein neuer Adminclient verbindet. In #155 habe ich aber auch die Möglichkeit eingebaut, dass der TestClient einfach seinen eigenen Testserver startet, was dieses Problem auch recht einfach umgeht.

**Comment by SKoschnicke** [comment]
Gut, dann setzen wir das so um.

**Comment by soerendomroes** [comment]
Ich würde das eher als Teil des Testclients einbauen (durch einen entsprechenden Request) und nicht für einen allgemeinen Adminclient machen, weil sich durch aus mehrere Adminclients verbinden können oder man (damit meine ich mich) zum testen auch mal gerne genau dein beschriebenes Verhalten erwartet.

**Comment by Xerus2000** [comment]
macht Sinn ja, kann man so machen. Der TestClient könnte sogar einfach das erste Score-Packet als Nullpunkt nehmen und jede weitere Score-Ausgabe damit subtrahieren, so ist der Server komplett außenvor. 
Für mich als Nutzer des TestClients ist es am Endeffekt egal wie, Hauptsache die Scores beginnen bei jedem neuen TestClient mit 0.

**Comment by Xerus2000** [comment]
Ist hier irgendwas passiert? Sonst schau ich mir das dann mal an.

**Comment by soerendomroes** [comment]
Ja, darum das Feedback required label. Müsstest du mal testen

**Comment by Xerus2000** [comment]
Nope, die Scores von den vorherigen Spielen bleiben.

**Comment by Xerus2000** [comment]
Soll das "TestModeRequest" das resetten oder sollte es dafür ein separates geben? So oder so sehe ich nirgends Logik, die dieses Issue fixen sollte.
