### ISSUE TITLE
ITeam needs subclass information to get deserialised

### ISSUE THREAD

**Issue by anarchuser** [software-challenge/backend#298]
Since the split from `PlayerColor` into the `ITeam` interface, the implementations of `Team`s are within the original plugin.
To serialise `ITeams` correctly, the information about which particular implementation to use needs to be passed, leading to ugly, plugin-dependant xml, so for instance:
```
<winner displayName="bluez">
  <color class="sc.api.plugins.TestTeam">BLUE</color>
</winner>
```
instead of the previous
```
<winner color="BLUE" displayName="bluez"/>
```

**Comment by anarchuser** [comment]
It might make sense to just use a custom xStream converter in the plugin.

**Comment by xerus2000** [comment]
Or maybe create a custom XStream converter in the sdk and register the Team via ServiceLoader as well.
