### ISSUE TITLE
Fehler in GameState.clone()

### ISSUE THREAD

**Issue by 0xhtml** [software-challenge/backend#417]
Die Methode `GameState.clone()` kopiert nicht alle Werte sondern verwendet teilweise Referenzen zur original Instanz.

Beispiel-Code:
```java
Team team = gameState.getCurrentTeam();
System.out.println(Arrays.toString(gameState.getPointsForTeam(team));
GameState clonedGameState = gameState.clone();
for (int i = 0; i < 15; i++) clonedGameState.performMove(clonedGameState.getPossibleMoves().get(0));
System.out.println(Arrays.toString(gameState.getPointsForTeam(team));
```
Ausgabe:
```
[0]
[10695]
```

Eigentlich dürften sich die Punkte für das nicht geklonte `gameState` nicht verändern.

**Comment by xeruf** [comment]
Fixed in 09802ecef fix(plugin/GameState): correctly clone fishes array (#415)
Release kommt morgen.
